#!/bin/bash

# The options used by this function parse with the code generated by this function.

# Set value.
FLAG=(
    --no-hash-bang
    --no-original-arguments
    --compact
    --no-error-invalid-options
    --no-error-require-arguments
    --no-rebuild-arguments
    --clean
)
VALUE=(
    --path-shell
    --sort
    --sort-type-flag
    --sort-type-value
    --sort-type-flag-value
    --sort-type-increment
    --sort-type-multivalue
    --debug-file
    --output-file
)
CSV=(
    'long:--with-end-options-double-dash,parameter:end_options_double_dash'
    'long:--without-end-options-double-dash,parameter:end_options_double_dash,flag_option:reverse'
    'long:--with-end-options-first-operand,parameter:end_options_first_operand'
    'long:--without-end-options-first-operand,parameter:end_options_first_operand,flag_option:reverse'
)

# Stop here.
source $(dirname $0)/code-generator-parse-options.function.sh
CodeGeneratorParseOptions \
    --compact \
    --no-error-invalid-options \
    --no-error-require-arguments \
    --no-hash-bang \
    --no-original-arguments \
    --no-rebuild-arguments \
    --without-end-options-double-dash \
    --clean
